# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_query_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
    ]
